---
- pipeline:
    name: check
    manager: independent
    trigger:
      gerrit:
        - event: comment-added
          comment: cisco-zuulv3-test
    success:
      gerrit:
        Verified: 1
    failure:
      gerrit:
        Verified: -1

- job:
    name: base
    run: playbooks/run.yaml
    nodeset:
      nodes:
        - name: ubuntu-xenial
          label: ubuntu-xenial
- job:
    name: test-job
    parent: base

- project:
    name: openstack/networking-cisco
    check:
      jobs:
        - test-job
