---
- pipeline:
    name: check
    manager: independent
    trigger:
      gerrit:
        - comment: cisco-zuulv3-test
    success:
      gerrit:
        Verified: 1
    failure:
      gerrit:
        Verified: -1

- jobs:
    - job:
        name: test-job

- project:
    name: openstack/networking-cisco
    check:
      jobs:
        - test-job
