---
- pipeline:
    name: check
    manager: independent
    trigger:
      gerrit:
        - comment: cisco-zuulv3-test
    success:
      gerrit:
        Verified: 1
    failure:
      gerrit:
        Verified: -1

- jobs:
    - job:
        name: test-job
        run: playbooks/run.yaml
        nodeset:
          nodes:
            - name: ubuntu-xenial
              label: ubuntu-xenial

- project:
    name: openstack/networking-cisco
    check:
      jobs:
        - test-job
